/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityPost {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface CommunityView {
  'id' : string,
  'members' : Array<Principal>,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface Event {
  'id' : string,
  'organizer' : Principal,
  'title' : string,
  'date' : Time,
  'tags' : Array<string>,
  'description' : string,
  'maxParticipants' : bigint,
}
export interface PostView {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'imageUrl' : [] | [string],
  'timestamp' : Time,
}
export interface ReputationReview {
  'scores' : ReputationScores,
  'comment' : string,
  'timestamp' : Time,
  'reviewee' : Principal,
  'reviewer' : Principal,
}
export interface ReputationScores {
  'teamwork' : bigint,
  'skillRelevance' : bigint,
  'reliability' : bigint,
  'contribution' : bigint,
}
export interface SocialLinks {
  'linkedin' : [] | [string],
  'twitter' : [] | [string],
  'instagram' : [] | [string],
  'website' : [] | [string],
  'github' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'socialLinks' : SocialLinks,
  'name' : string,
  'designation' : string,
  'year' : bigint,
  'avatarUrl' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSkill' : ActorMethod<[string], undefined>,
  'applyToEvent' : ActorMethod<[string], undefined>,
  'approveApplication' : ActorMethod<[string, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentOnPost' : ActorMethod<[string, string], undefined>,
  'createCommunity' : ActorMethod<[string, string, string, string], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, Time, Array<string>, bigint],
    undefined
  >,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'createPost' : ActorMethod<[string, string, [] | [string]], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllCommunities' : ActorMethod<[], Array<CommunityView>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityPosts' : ActorMethod<[string], Array<CommunityPost>>,
  'getEventApplications' : ActorMethod<[string], Array<Principal>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getGlobalFeed' : ActorMethod<[], Array<PostView>>,
  'getPersonalizedFeed' : ActorMethod<[], Array<PostView>>,
  'getReputation' : ActorMethod<[Principal], Array<ReputationReview>>,
  'getSkills' : ActorMethod<[Principal], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCommunity' : ActorMethod<[string], undefined>,
  'leaveCommunity' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'postCommunityMessage' : ActorMethod<[string, string], undefined>,
  'rejectApplication' : ActorMethod<[string, Principal], undefined>,
  'removeSkill' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBySkill' : ActorMethod<
    [string],
    Array<[UserProfile, Array<string>, Array<ReputationReview>]>
  >,
  'submitReputationReview' : ActorMethod<
    [Principal, ReputationScores, string],
    undefined
  >,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];