/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const SocialLinks = IDL.Record({
  'linkedin' : IDL.Opt(IDL.Text),
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'github' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'socialLinks' : SocialLinks,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'year' : IDL.Nat,
  'avatarUrl' : IDL.Text,
  'department' : IDL.Text,
});
export const CommunityView = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'organizer' : IDL.Principal,
  'title' : IDL.Text,
  'date' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'maxParticipants' : IDL.Nat,
});
export const CommunityPost = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const PostView = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'imageUrl' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const ReputationScores = IDL.Record({
  'teamwork' : IDL.Nat,
  'skillRelevance' : IDL.Nat,
  'reliability' : IDL.Nat,
  'contribution' : IDL.Nat,
});
export const ReputationReview = IDL.Record({
  'scores' : ReputationScores,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'reviewee' : IDL.Principal,
  'reviewer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSkill' : IDL.Func([IDL.Text], [], []),
  'applyToEvent' : IDL.Func([IDL.Text], [], []),
  'approveApplication' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentOnPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCommunity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllCommunities' : IDL.Func([], [IDL.Vec(CommunityView)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityPosts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getEventApplications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getGlobalFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getPersonalizedFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getReputation' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ReputationReview)],
      ['query'],
    ),
  'getSkills' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCommunity' : IDL.Func([IDL.Text], [], []),
  'leaveCommunity' : IDL.Func([IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'postCommunityMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectApplication' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removeSkill' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBySkill' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Tuple(UserProfile, IDL.Vec(IDL.Text), IDL.Vec(ReputationReview))
        ),
      ],
      ['query'],
    ),
  'submitReputationReview' : IDL.Func(
      [IDL.Principal, ReputationScores, IDL.Text],
      [],
      [],
    ),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const SocialLinks = IDL.Record({
    'linkedin' : IDL.Opt(IDL.Text),
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'github' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'socialLinks' : SocialLinks,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'year' : IDL.Nat,
    'avatarUrl' : IDL.Text,
    'department' : IDL.Text,
  });
  const CommunityView = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'organizer' : IDL.Principal,
    'title' : IDL.Text,
    'date' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'maxParticipants' : IDL.Nat,
  });
  const CommunityPost = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const PostView = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'imageUrl' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const ReputationScores = IDL.Record({
    'teamwork' : IDL.Nat,
    'skillRelevance' : IDL.Nat,
    'reliability' : IDL.Nat,
    'contribution' : IDL.Nat,
  });
  const ReputationReview = IDL.Record({
    'scores' : ReputationScores,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'reviewee' : IDL.Principal,
    'reviewer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSkill' : IDL.Func([IDL.Text], [], []),
    'applyToEvent' : IDL.Func([IDL.Text], [], []),
    'approveApplication' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentOnPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCommunity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllCommunities' : IDL.Func([], [IDL.Vec(CommunityView)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityPosts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getEventApplications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGlobalFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getPersonalizedFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getReputation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReputationReview)],
        ['query'],
      ),
    'getSkills' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCommunity' : IDL.Func([IDL.Text], [], []),
    'leaveCommunity' : IDL.Func([IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'postCommunityMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectApplication' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removeSkill' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBySkill' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Tuple(UserProfile, IDL.Vec(IDL.Text), IDL.Vec(ReputationReview))
          ),
        ],
        ['query'],
      ),
    'submitReputationReview' : IDL.Func(
        [IDL.Principal, ReputationScores, IDL.Text],
        [],
        [],
      ),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };